#ifndef __SYSTEM_DEFINE_H
#define __SYSTEM_DEFINE_H

// State Definitions
enum State { MATERIAL_CHECK, START_PRODUCTION, PROCESS_CONTINUE, PRODUCT_OUTPUT, ERROR, EMERGENCY_STOP };

// Error Codes
enum ErrorCode { NO_ERROR, SENSOR_ERROR, ACTUATOR_ERROR, MATERIAL_ERROR, PROCESS_ERROR };

enum State currentState = MATERIAL_CHECK;
enum ErrorCode errorCode = NO_ERROR;

#endif